Social/urls.py
from django.contrib import admin
from django.urls import path, include
import home

app_name = "account"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('post/', include('post.urls', namespace='post')),
    path('follow/', include('follow.urls', namespace='follow')),
]

account/urls.py
from django.urls import path
from account.views import UserRegisterView, UserLoginView, UserLogoutView, UserProfileView, UserPasswordResetView, \
    UserPasswordResetDoneView, UserPasswordResetConfirmView, UserPasswordResetCompleteView

app_name = 'account'
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='user_register'),
    path('login/', UserLoginView.as_view(), name='user_login'),
    path('logout/', UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>', UserProfileView.as_view(), name='user_profile'),
    path('reset/', UserPasswordResetView.as_view(), name='user_reset_password'),
    path('reset/done', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(), name='user_reset_confirm'),
    path('confirm/complete', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

home/urls.py
from django.urls import path
from home.views import HomeView, trigger_404


app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('trigger-404/', trigger_404),
]

post/urls.py
from django.urls import path

from post.views import PostDetailView, PostDeleteView, PostEditView, PostCreatView, PostAddReplyView, PostLikeView

app_name = 'post'
urlpatterns = [
    path('details/<int:post_id>/<slug:post_slug>', PostDetailView.as_view(), name='post_detail'),
    path('delete/<int:post_id>', PostDeleteView.as_view(), name='post_delete'),
    path('edit/<int:post_id>', PostEditView.as_view(), name='post_edit'),
    path('create', PostCreatView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>', PostAddReplyView.as_view(), name='reply_comment'),
    path('like/<int:post_id>/', PostLikeView.as_view(), name='post_like'),
]

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericRelation
from like.models import Like


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    title = models.CharField(max_length=255, default='python')
    body = models.TextField()
    slug = models.SlugField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    like = GenericRelation(Like)

    class Meta:
        ordering = ('-created_at','title')
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post:post_detail', args=[self.id, self.slug])


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomments')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomments')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomments', blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    body = models.TextField(max_length=400)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return f'{self.user} - {self.body[:30]}'

post/forms.py
from django import forms

from post.models import Post, Comment


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body', 'title')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control'})
        }


class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'class': 'form-control', 'col':5, 'row': 3})
        }

post/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.decorators import method_decorator
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.utils.text import slugify

from like.models import Like
from post.forms import PostUpdateForm, CommentForm, CommentReplyForm
from post.models import Post, Comment
from django.contrib.contenttypes.models import ContentType


class PostDetailView(View):
    form_class = CommentForm
    form_reply_class = CommentReplyForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'], slug=kwargs['post_slug'])
        return super().setup(request, *args, **kwargs)


    def get(self, request, *args, **kwargs):
        #post = Post.objects.get(pk=post_id, slug=post_slug)
        post = self.post_instance
        comments = post.pcomments.filter(is_reply=False)
        post_content_type = ContentType.objects.get_for_model(Post)
        pLikes = Like.objects.filter(content_type=post_content_type, object_id=post.id)

        return render(request, 'show.html', {'post': post, 'comments': comments,
                                             'form': self.form_class, 'reply_from': self.form_reply_class,
                                             'votes':pLikes})

    # @login_required =>function decorator x
    @method_decorator(login_required)  # chon baraye yek method mikhahim az method decorator estefade mishe
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = self.post_instance
            new_comment.save()
            messages.success(request, 'comment is submitted', 'success')
        return redirect('post:post_detail', self.post_instance.id, self.post_instance.slug)


class PostDeleteView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = Post.objects.get(pk=post_id)
        if post.user.id == request.user.id:
            post.delete()
            messages.success(request, 'Post is Deleted successfully', 'success')
        else:
            messages.error(request, 'Post can not be deleted', 'error')
        return redirect('home:home')


class PostEditView(LoginRequiredMixin, View):
    form_class = PostUpdateForm

    def setup(self, request, *args, **kwargs):
        self.post_instance = Post.objects.get(pk=kwargs['post_id'])
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        post = self.post_instance
        if not post.user.id == request.user.id:
            messages.error(request, 'Post can not be edited', 'error')
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, post_id):
        post = self.post_instance
        form = self.form_class(instance=post)
        return render(request, 'update.html', {'form': form})

    def post(self, request, post_id):
        post = self.post_instance
        form = self.form_class(request.POST, instance=post)
        if form.is_valid():
            newPost = form.save(commit=False)
            newPost.slug = slugify(form.cleaned_data['title'][:30])
            newPost.save()

            messages.success(request, 'update successfully', 'success')
            return redirect('post:post_detail', post.id, post.slug)


class PostCreatView(LoginRequiredMixin, View):
    form_class = PostUpdateForm

    def get(self, request):
        form = self.form_class
        return render(request, 'update.html', {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = request.user
            new_post.slug = slugify(form.cleaned_data['title'][:30])
            new_post.save()
            messages.success(request, 'create successfully', 'success')
            return redirect('post:post_detail', new_post.id, new_post.slug)


class PostAddReplyView(LoginRequiredMixin, View):
    form_class = CommentReplyForm

    def post(self, request, post_id, comment_id):
        post = get_object_or_404(Post, id=post_id)
        comment = get_object_or_404(Comment, id=comment_id)
        form = self.form_class(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.post = post
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            messages.success(request,'nazare shoma sabt shod', 'success')
        return redirect('post:post_detail', post.id, post.slug)


class PostLikeView(LoginRequiredMixin, View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)

        like = Like.objects.filter(user=request.user,
                                   content_type=ContentType.objects.get_for_model(Post), object_id=post.id)
        if like.exists():
            messages.error(request, 'Like is submitted before','error')
        else:
            Like.objects.create(user=request.user, content_object=post)
            messages.success(request,'Like is submit')
        return redirect('post:post_detail', post.id,post.slug )

post/templates/show.html
{% extends 'base.html' %}

{% block title %} {{ post.title}} {% endblock %}
{% block content %}
    <h2>
         {{ post.title}}
    </h2>
<div class="col-md-6">
    <p>
        {{ post.body }}
    </p>

    <footer>
        <a href="{% url 'account:user_profile' post.user.id %}"> {{ post.user.username}} </a> | {{post.created_at|date:"Y-M-D" }}
        {% if post.user.id == request.user.id %}
        <div>
            <a href="{% url 'post:post_delete' post.id %}" class="btn btn-danger">DELETE</a>
            <a href="{% url 'post:post_edit' post.id %}" class="btn btn-success">UPDATE</a>
        </div>
        {% endif %}
    </footer>
    {% if request.user.is_authenticated %}
    <a href="{% url 'post:post_like' post.id %}" class="btn btn-primary col-md-2">Like</a>
    <br>
    <div class="card" style="margin-top:15px">
    <div class="card-body">
        <form action="" method="post" name="comment">
            {% csrf_token %}
             {{ form.as_p }}
            <input type="submit" value="submit">
        </form>

    </div>
</div>
    {% endif %}
    <hr/>
    <div class="col-lg-12">
        <p>
           count: {{comments.count}}
           reply count: {{comments.rcomments.count}}
        </p>
        <p>
            likeCount = {{votes.count}}
        </p>
        {% for comment in comments %}
        <div class="card bg-dark text-white">
            <p class="card-header">
                {{ comment.user }} | {{comment.created_at|timesince}}
            </p>
              <p class="card-body">
             {{ comment.body }}
                </p>
            {% if request.user.is_authenticated %}
                <div class="col-sm-6" style="padding:5px;">
                    <form action="{% url 'post:reply_comment' post.id comment.id %}" method="post">
                    {% csrf_token %}
                    {{reply_from.as_p}}
                    <input type="submit" value="submit">
                </form>
                </div>
            {% endif %}
            {% with replies=comment.rcomments.all %}
                {% for reply in replies %}
                        <p>
                         {{reply.user}}
                         </p>
            <p>
                {{ reply.body }}
            </p>
                {% endfor %}
            {% endwith %}

        </div>
        <br>
        {% empty %}
        <p>
            no Comments Yet ......
        </p>
        {% endfor %}
    </div>
</div>
<hr/>

{% endblock %}

post/templates/update.html
{% extends 'base.html' %}

{% block title %} {{ post.title}} {% endblock %}
{% block content %}
    <h2>
         {{ post.title}}
    </h2>
<div class="col-md-6">
    <form action="" method="post" >
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="submit">
    </form>
</div>


{% endblock %}