Social/urls.py
from django.contrib import admin
from django.urls import path, include
import home

app_name = "account"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('account/', include('account.urls', namespace='account')),
    path('post/', include('post.urls', namespace='post')),
    path('follow/', include('follow.urls', namespace='follow')),
]

account/urls.py
from django.urls import path
from account.views import UserRegisterView, UserLoginView, UserLogoutView, UserProfileView, UserPasswordResetView, \
    UserPasswordResetDoneView, UserPasswordResetConfirmView, UserPasswordResetCompleteView

app_name = 'account'
urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='user_register'),
    path('login/', UserLoginView.as_view(), name='user_login'),
    path('logout/', UserLogoutView.as_view(), name='user_logout'),
    path('profile/<int:user_id>', UserProfileView.as_view(), name='user_profile'),
    path('reset/', UserPasswordResetView.as_view(), name='user_reset_password'),
    path('reset/done', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>', UserPasswordResetConfirmView.as_view(), name='user_reset_confirm'),
    path('confirm/complete', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

home/urls.py
from django.urls import path
from home.views import HomeView, trigger_404


app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('trigger-404/', trigger_404),
]

templates/inc/messages.html
{%if messages%}
    {% for msg in messages%}
        <p class="alert alert-{{msg.tags}}"> {{msg}} </p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'account:user_logout' %}">Log out</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'account:user_profile' request.user.id %}">Profile</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'account:user_register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'account:user_login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>